jobs:
  - type: runSh
    name: hello
    steps:
      - IN: simple_pipe_repo
        switch: off
      - TASK:
        - script: echo "Hello, World!"
        - script: env | grep "SIMPLE_PIPE_REPO"
        - script: cat $SIMPLE_PIPE_REPO_PATH/gitRepo/foo.json | jq .
    flags:
      - alpha
      - gamma
  - type: runSh
    name: hello_again
    steps:
      - IN: simple_pipe_repo
        switch: off
      - TASK:
        - script: echo "Hello, World! Again."
    flags:
      - alpha
      - charlie
      - beta
      - delta
      - foxtrot
      - echo
      - golf
      - india
      - hotel
