jobs:
  - type: runSh
    name: hello
    steps:
      - IN: simple_pipe_repo
        switch: off
      - TASK:
        - script: echo "Hello, World!"
  - type: runSh
    name: hello_again
    steps:
      - TASK:
        - script: echo "Hello, World! Again."
